let familyTree = [
    {"key":1, "name":"Juan (Jean) Duhagon", "birth": "1/12/1833 - Iholdy (Francia)", "marriage": "casamiento: ? - Bs As", "spouse": "Margarita Mertinez", "link": "/juan-duhagon"},
    {"key":2, "name":"Bernardo Duhagon","parent":1, "birth": "? - Bs As", "marriage": "casamiento: ? - Chacabuco", "spouse": "Maria Polonia Marquinez", "link": "/bernardo-duhagon"},
    {"key":3, "name":"Juan Duhagon", "parent":2, "birth": "1885 - Chacabuco", "marriage": "", "spouse": "Juana Dolores Fluttaz", "link": "/juan-duhagon-2"},
    {"key":4, "name":"Fernando Duhagon", "parent":2, "birth": "1886 - Chacabuco", "marriage": "", "spouse": "Maria Carron", "link": "/fernando-duhagon"},
    {"key":5, "name":"Margarita Duhagon", "parent":2, "birth": "1888 - Chacabuco", "marriage": "", "spouse": "Santiago Fluttaz", "link": "/margarita-duhagon"},
    {"key":6, "name":"Maria Balbina Duhagon", "parent":2, "birth": "1889 - Chacabuco", "marriage": "", "spouse": "","link": "/maria-balbina-duhagon"},
    {"key":7, "name":"Gregorio Duhagon", "parent":2, "birth": "1891 - Chacabuco", "marriage": "", "spouse": "María Sharry", "link": "/gregorio-duhagon"},
    {"key":8, "name":"Maria Duhagon", "parent":2, "birth": "1892 - Chacabuco", "marriage": "", "spouse": "", "link": "/maria-duhagon"},
    {"key":9, "name":"Bernardo Duhagon", "parent":2, "birth": "1893 - Chacabuco", "marriage": "", "spouse": "", "link": "/bernardo-duhagon-2"},
    {"key":10, "name":"Pedro Duhagon", "parent":2, "birth": "6/8/1896 - Chacabuco", "marriage": "casamiento: 25/4/1925 - Chacabuco", "spouse": "Maria Polonia Carricart", "link": "/pedro-duhagon"},
    {"key":11, "name":"Esther Duhagon", "parent":10, "birth": "17/02/1926 - Junin", "marriage": "", "spouse": "Juan Barbero"},
    {"key":12, "name":"Elda (Tita) Duhagon", "parent":10, "birth": "06/08/1927 - Junin", "marriage": "", "spouse": "Obdulio Miranda"},
    {"key":13, "name":"Bernardo Fernando Duhagon", "parent":10, "birth": "08/08/1929 - Junin", "marriage": "", "spouse": "Elba Duhagon"},
    {"key":14, "name":"Obdulio Duhagon", "parent":10, "birth": "19/11/1930 - Junin", "marriage": "", "spouse": "?"},
    {"key":15, "name":"Elsa Duhagon", "parent":10, "birth": "29/01/1932 - Junin", "marriage": "", "spouse": "Hilario Patricio Teppaz"},
    {"key":16, "name":"Norma Duhagon", "parent":10, "birth": "08/04/1933 - Junin", "marriage": "", "spouse": "Celso Moguet"},
    {"key":17, "name":"Nestor Duhagon", "parent":10, "birth": "08/04/1933 - Junin", "marriage": "", "spouse": "Ana Maria (Beba) Garcia"},
    {"key":18, "name":"Olga Duhagon", "parent":10, "birth": "25/09/1934 - Junin", "marriage": "", "spouse": "Luis (Coco) Tapia"},
    {"key":19, "name":"Horacio Duhagon", "parent":10, "birth": "27/01/1936 - Junin", "marriage": "", "spouse": "Elida M. Balocco"},
    {"key":20, "name":"Nilda Duhagon", "parent":10, "birth": "27/01/1936 - Junin", "marriage": "", "spouse": "Ricardo Benitez"},
    {"key":21, "name":"Pedro Ruben Duhagon", "parent":10, "birth": "13/05/1937 - Junin", "marriage": "", "spouse": ""},
    {"key":22, "name":"Edgardo Duhagon", "parent":10, "birth": "30/03/1940 - Junin", "marriage": "", "spouse": "Marta Forzano"},
]